lastre1208/GameProduction_Team_B

Big Wave prototype/Assets/Script/AttackControl.cs
Big Wave prototype/Assets/Script/ControlGamespeed.cs

攻撃フラグの変数名の変更

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/AttackPatternOfEnemy.cs
Big Wave prototype/Assets/Script/AttackTimingOfEnemy.cs

一部コードの修正と第二形態を実装しました。
操作的には何形態でも作れますが二形態までしか動きません。
なお第二形態のON&OFFはbool型のsecondFormから切り替えてください

コードの修正と第二形態実装しました

---

Big Wave prototype/Assets/Prefab/RopePrefab.prefab
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/AttackControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs

・プレイヤーについているAttackControlの〇〇TrickCostPercentから消費トリック(最大トリックの%)、○○Damage(敵に与えるダメージ量)をそれぞれ変更できます
・Jキーで強攻撃、Kキーで中攻撃、Lキーで弱攻撃ができます
・ただXboxコントローラーのボタン対応ができていないので誰かコントローラーを持っている方はAttackControlのボタン操作のところを書き換えてください

プレイヤーの攻撃を変更しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity

SampleSceneのファイルがプッシュできていなかったため、再プッシュを行いました。

Sceneのプッシュを行いました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/AttackControl.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Controller.cs
Big Wave prototype/Assets/Script/PlayerScript/Controller.cs.meta
Big Wave prototype/Assets/Script/PlayerScript/JumpControl.cs
Big Wave prototype/Assets/Script/PlayerScript/MoveControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs

コントローラー関係の処理をControllerスクリプトに統合させました

---

Big Wave prototype/Assets/Scenes/ClearScene.unity
Big Wave prototype/Assets/Scenes/GameoverScene.unity
Big Wave prototype/Assets/Scenes/MenuScene.unity
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyScript/Enemy.cs
Big Wave prototype/Assets/Script/EtcScript/SceneControlManager.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs
Big Wave prototype/ProjectSettings/EditorBuildSettings.asset
Big Wave prototype/ProjectSettings/TagManager.asset

・敵死亡時クリアシーンに移行するようにしました
・プレイヤー死亡時ゲームオーバーシーンに移行するようにしました
・メニューシーンからゲームをプレイできるようにしました

シーン遷移関係を更新しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyScript/AttackPatternOfEnemy.cs
Big Wave prototype/Assets/Script/EnemyScript/AttackTimingOfEnemy.cs

・敵の行動、攻撃パターンを何形態でも作れるようにしました
・AttackTimingOfEnemyスクリプトのFormから形態ごとの形態突入条件や行動の変更が可能
・AttackPatternOfEnemyスクリプトのFormから形態ごとの攻撃パターンや攻撃の確率の変更が可能
・AttackPatternOfEnemyのAttackProbabilityからそれぞれの技の確率の変更が行えます
～～～注意～～～
・AttackTimingOfEnemyスクリプトとAttackPatternOfEnemyスクリプトのFormの要素数は揃えてください(例えば片方3形態、片方10形態あるのはダメ)

敵の攻撃の処理を改善しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyScript/AttackPatternOfEnemy.cs
Big Wave prototype/Assets/Script/EnemyScript/AttackTimingOfEnemy.cs
Big Wave prototype/Assets/Script/EnemyScript/Enemy.cs
Big Wave prototype/Assets/Script/EnemyScript/InstantiateWave.cs
Big Wave prototype/Assets/Script/EnemyScript/RandomMove.cs
Big Wave prototype/Assets/Script/EtcScript/AttackOfBullet.cs
Big Wave prototype/Assets/Script/EtcScript/ControlGamespeed.cs
Big Wave prototype/Assets/Script/EtcScript/DeleteObject.cs
Big Wave prototype/Assets/Script/EtcScript/ForwardMove.cs
Big Wave prototype/Assets/Script/EtcScript/InstantiateBuildings.cs
Big Wave prototype/Assets/Script/EtcScript/InstantiateRope.cs
Big Wave prototype/Assets/Script/EtcScript/InstantiateSeaTest.cs
Big Wave prototype/Assets/Script/EtcScript/LimitMove.cs
Big Wave prototype/Assets/Script/EtcScript/MoveManager.cs
Big Wave prototype/Assets/Script/EtcScript/ResultDisplay.cs
Big Wave prototype/Assets/Script/EtcScript/RopeEffect.cs
Big Wave prototype/Assets/Script/EtcScript/SceneControlManager.cs
Big Wave prototype/Assets/Script/EtcScript/StatusDisplay.cs
Big Wave prototype/Assets/Script/EtcScript/TimeDisplay.cs
Big Wave prototype/Assets/Script/EtcScript/Wave.cs
Big Wave prototype/Assets/Script/PlayerScript/AttackControl.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Controller.cs
Big Wave prototype/Assets/Script/PlayerScript/JudgeTouchWave.cs
Big Wave prototype/Assets/Script/PlayerScript/JumpControl.cs
Big Wave prototype/Assets/Script/PlayerScript/MoveControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs

・プログラム(自分の書いたところ)を整理しました(主にコメント化)
・playerスクリプトに書かれてた攻撃時の効果音だすコードは全てAttackControlスクリプトに移動させました 
・誰が書いたコードかわかるようにしておきました(//☆○○が書いた、という書き方で書いてます)
//☆○○が書いたの名前のとこは気に入らなかったら後で自分で書き直してもらっても大丈夫です

全体的にプログラムの整理をしました

---

Big Wave prototype/Assets/Material/Wave White_Blue.mat
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/CommandPatterns.cs
Big Wave prototype/Assets/Script/PlayerScript/CommandPatterns.cs.meta
Big Wave prototype/Assets/Script/PlayerScript/CommandTrick.cs
Big Wave prototype/Assets/Script/PlayerScript/CommandTrick.cs.meta
Big Wave prototype/ProjectSettings/InputManager.asset

ジャンプ中に既定のボタンの組み合わせをする事で特定の処理を呼び出せるようにしました。(今はデバックログを呼ぶだけ)
CommandPatternsでコマンドが何種類存在するかを指定し、Sequenceでいくつのボタンの組み合わせになるかを指定します。
ElementにABXYを一文字ずつ入れる事でコマンドを自由に組み立てる事ができます。
現状PatternName内にある文字列とスクリプト上の文字列が異なると正常に処理が行えないので、名前を変える際はスクリプト上の名前も変更、追加するようにしてください。

コマンド機能を追加しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyScript/Enemy.cs
Big Wave prototype/Assets/Script/EnemyScript/SelectActionOfEnemy.cs
Big Wave prototype/Assets/Script/EtcScript/AttackOfBullet.cs
Big Wave prototype/Assets/Script/EtcScript/ControlGamespeed.cs
Big Wave prototype/Assets/Script/EtcScript/ForwardMove.cs
Big Wave prototype/Assets/Script/EtcScript/InstantiateRope.cs
Big Wave prototype/Assets/Script/EtcScript/LimitMove.cs
Big Wave prototype/Assets/Script/EtcScript/MoveManager.cs
Big Wave prototype/Assets/Script/EtcScript/RopeEffect.cs
Big Wave prototype/Assets/Script/EtcScript/StatusDisplay.cs
Big Wave prototype/Assets/Script/EtcScript/Wave.cs
Big Wave prototype/Assets/Script/PlayerScript/AttackControl.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickControl.cs
Big Wave prototype/Assets/Script/PlayerScript/CommandTrick.cs
Big Wave prototype/Assets/Script/PlayerScript/Controller.cs
Big Wave prototype/Assets/Script/PlayerScript/JudgeTouchWave.cs
Big Wave prototype/Assets/Script/PlayerScript/JumpControl.cs
Big Wave prototype/Assets/Script/PlayerScript/MoveControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs

・自分の書いたところのみプロパティを追加しました(他のところは後程やります)
・コードの変数部分を書き換えたのでもしかしたら一部ステータスなどが変更されてるかもなのでもし変わっていたら調整お願いします

コード(自分の書いたところのみ)にプロパティを追加しました

---

Big Wave prototype/Assets/Scenes/ClearScene.unity
Big Wave prototype/Assets/Scenes/GameoverScene.unity
Big Wave prototype/Assets/Scenes/MenuScene.unity

メニュー画面上のボタンをゲームパッドからの入力で操作できる機能を実装しました。
・変更箇所は、MenuScene・GameoverScene・ClearSceneの3つです。
・Canvasの子として配置されているButtonとEventSystemのInspectorウィンドウ内の項目を設定することで機能を実装できたの　　
　で、追加や編集を行ったスクリプトはありません。

ゲームパッドによるメニュー操作機能の実装

---

Big Wave prototype/Assets/Scenes/ClearScene.unity
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/TrickControl.cs
Big Wave prototype/Assets/Script/ScoreScript/ManagementOfScore.cs
Big Wave prototype/Assets/Script/ScoreScript/ManagementOfScore.cs.meta
Big Wave prototype/Assets/Script/ScoreScript/ResultDisplay.cs
Big Wave prototype/Assets/Script/ScoreScript/ScoreDisplay.cs
Big Wave prototype/Assets/Script/ScoreScript/ScoreDisplay.cs.meta
Big Wave prototype/Assets/Script/ScoreScript/TimeDisplay.cs
Big Wave prototype/ProjectSettings/TagManager.asset

ManagementOfScoreを追加しました。また、TrickControlとResultDisplayにコードの追加を行いました。
TimeDisplayに制限時間をインスペクターウィンドウ上から変更できるようにしました。
ManagementOfScoreに以下の機能を実装しました。
・クリア時の残り時間のスコア化と倍率設定
・クリア時のトリックゲージ残量のスコア化と倍率設定
・トリック成功時のスコア量の設定
・被ダメの評価と各評価段階の設定
　（現時点では5段階に評価を区切り、段階ごとに評価を受ける条件となる被ダメ回数とスコア量の調節を行う形式になってい　
　　ます。クリア時に判定された評価をもとに、最終スコアに加点を行っています。）
被ダメの評価について少しわかりづらいかもしれないので、不備や改善点が確認できたら教えてください。

スコア機能を実装しました。

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/BuffOfPlayer.cs
Big Wave prototype/Assets/Script/PlayerScript/TrickControl.cs

今コロナにかかってはいますが今のとこ無症状なのでご心配なく(無理ない範囲でやる気があるときに制作の作業もしようと思います)

バフ関係のスクリプトを修正しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyBulletScript/AttackOfBullet.cs
Big Wave prototype/Assets/Script/EtcScript/StatusDisplay.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickControl.cs
Big Wave prototype/Assets/Script/PlayerScript/Player.cs
Big Wave prototype/Assets/Script/PlayerScript/ProcessFeverPoint.cs
Big Wave prototype/Assets/Script/PlayerScript/ProcessFeverPoint.cs.meta
Big Wave prototype/Assets/Script/PlayerScript/TrickControl.cs

Playerスクリプトからフィーバーゲージの最大値、ProcessFeverPointスクリプトからFeverPointのたまり方とかフィーバー状態の効果、効果時間が変えられます
スクリプトが汚いので後程コメント化とかしておきます

フィーバーゲージのシステムを作りました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickScript/ChangeChargeTrick.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTrickScript/ChangeChargeTrickEffect.cs

・波に乗っているまたはジャンプしている時は倍率がだんだん増えていき、そうでない時は倍率がどんどん減っていくようになりました
・ChangeChargeTrickスクリプトから倍率が減る速度(増える時を1として)も変更できるようにしました

波に乗っているまたはジャンプしている時は倍率がだんだん増えていき、そうでない時は倍率がどんどん減っていく仕様を実装しました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Scenes/ToMainLoadScene.unity
Big Wave prototype/Assets/Scenes/ToMainLoadScene.unity.meta
Big Wave prototype/Assets/Script/EtcScript/LoadMainScene.cs
Big Wave prototype/Assets/Script/EtcScript/LoadMainScene.cs.meta
Big Wave prototype/Assets/Script/EtcScript/SceneControlManager.cs
Big Wave prototype/ProjectSettings/EditorBuildSettings.asset

　仕組みとしては今までボタン押す->メインシーンだったのを、ボタン押す->ロードシーン->そこで読み込み->読み込み完了後メインシーンに変更して一度ロードシーンを経由させるようにしました
　ロード画面作る過程でメインシーン(ゲームのシーン)に入った時にSkyBoxの影響か明るさが暗くなってしまっていたのでSkyBoxMaterialからMaterialを一旦外して、MainCameraにSkyBoxコンポーネントを追加してそこにMaterialを入れたら解決しました

仮ですがロード画面を作ってみました

---

Big Wave prototype/Assets/Material/Wall Preview.mat
Big Wave prototype/Assets/Material/Wall Preview.mat.meta
Big Wave prototype/Assets/Prefab/Object/Bullet Wall Preview.prefab
Big Wave prototype/Assets/Prefab/Object/Bullet Wall Preview.prefab.meta
Big Wave prototype/Assets/Prefab/Object/Bullet Wall.prefab
Big Wave prototype/Assets/Prefab/Object/Bullet Wall.prefab.meta
Big Wave prototype/Assets/Prefab/Object/Wall Area.prefab
Big Wave prototype/Assets/Prefab/Object/Wall Area.prefab.meta
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EnemyBulletScript/ToggleColliderOfWallBullet.cs
Big Wave prototype/Assets/Script/EnemyBulletScript/ToggleColliderOfWallBullet.cs.meta
Big Wave prototype/Assets/Script/EnemyBulletScript/WallBullet.cs
Big Wave prototype/Assets/Script/EnemyBulletScript/WallBullet.cs.meta
Big Wave prototype/Assets/Script/EnemyScript/EnemyActionType/EnemyActionTypeShotWall.cs
Big Wave prototype/Assets/Script/EnemyScript/EnemyActionType/EnemyActionTypeShotWall.cs.meta

追加したスクリプト
・EnemyActionTypeShotWall　・WallBullet　・ToggleColliderOfWallBullet
追加オブジェクト
・Bullet Wall　・Bullet Wall Preview　・Wall Area　・Wall Preview（Bullet Wall Preview用のマテリアル）
・ShotWall（空のオブジェクト）
機能説明
・EnemyActionTypeShotWall
　壁の生成範囲を指定するオブジェクトの生成についての管理や各要素の値野設定を行っています。このスクリプトがアタッチ　
　されているShotWall内で要素の値を調整できます。
・WallBullet
　攻撃範囲や攻撃判定を持つ壁、攻撃範囲の予告表示などの大きさ・位置調整を行っています。また、WallAreaに加えられた力　
　を各Bullet Wallに加えて動かす処理なども行っています。
　
・ToggleColliderOfWallBullet
　プレイヤーがいずれかのBullet Wallに接触したら、生成されたすべてのBullet Wallのコライダーを無効化するようにしていま
　す。
調整項目について
・Wall Prefab -> 攻撃判定を持つ壁オブジェクトの設定を設定します。
・Wall Area Prefab -> wall Prefabの生成範囲を設定します。生成されたwall Prefabはこのオブジェクトの子となります。
・Wall Preview Prefab -> 攻撃範囲の予告表示として生成するオブジェクトを設定します。
・Ground -> 壁の生成範囲の底辺を合わせるオブジェクトを設定します。
・Width・Height -> …

エラーメッセージ攻撃を実装しました。

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/HoverJump.cs
Big Wave prototype/Assets/Script/PlayerScript/JudgeOnceReachedHighestPoint_Jumping.cs
Big Wave prototype/Assets/Script/PlayerScript/JudgeOnceReachedHighestPoint_Jumping.cs.meta
Big Wave prototype/Assets/Script/PlayerScript/Jump-related/Jump.cs

ジャンプしてから最高点に一度も上がっていない間はホバージャンプが発生しないようになりました

ホバージャンプの仕様を修正しました

---

Big Wave prototype/Assets/Script/EnemyBulletScript/WallBullet.cs
Big Wave prototype/Assets/Script/EnemyScript/EnemyActionType/EnemyActionTypeShotWall.cs

変更点
・敵オブジェクトの移動の影響を受けて、壁や予告法事のずれが生じてしまう不具合を修正しました。
・必要がなくなった変数を削除しました。
・予告表示を生成する際、SpawnPointOfWallPreviewのz座標を参照するように修正し、SpawnPointOfWallPreviewの位置を変え　
　ることで予告を表示する位置を変更できるようにしました。
・壁を生成する際、ShotWallPosの位置を参照するように修正し、ShotWallPosの位置を変えることで壁攻撃の生成位置を変更で
　きるようにしました。
仕様の変更・追加点や不具合を発見した場合は報告お願いします。

壁攻撃の不具合を修正しました。

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/UIScript/TrickPointDisplay.cs

UIのスクリプトの修正作業終わったので素材さえあればいつでも円状のUI入れられます

トリックゲージのスクリプトを修正しました

---

Big Wave prototype/Assets/Prefab/Object/Particle/EnemyDamegeEffect.prefab
Big Wave prototype/Assets/Scenes/ClearScene.unity
Big Wave prototype/Assets/Scenes/GameoverScene.unity
Big Wave prototype/Assets/Scenes/MenuScene.unity
Big Wave prototype/Assets/Script/EtcScript/InstantiateBuildings.cs
Big Wave prototype/Assets/Script/UIScript/ButtonEffect/CustomButtonEventsManager.cs
Big Wave prototype/Assets/Script/UIScript/ButtonEffect/MenuEffectController.cs
Big Wave prototype/Assets/Script/UIScript/ButtonEffect/NavigationEventsManager.cs

・クロマクロがダメージを受けたときに生成されるパーティクルのパラメータを調整しました。
・メニュー画面と同様のエフェクトを、クリア画面やゲームオーバー画面にも実装しました。
　現時点では、設定がやりづらくなってしまっているので後ほどまた修正します。

エフェクトについて、修正や実装を行いました。

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/PlayerScript/MoveLeftAndRight.cs

・Is Inertia Enabledのチェックを切り替えることで、今までの慣性なしの移動と慣性ありの移動
　を切り替えられるようにしました。
・Is Center Pull Enabledのチェックを切り替えることで、中央に引き寄せられる力の有効、無効化
　を選択できるようにしました。
　
・各項目でスピード等の調整ができます。
不備や変更点があったら教えてください。

移動に慣性を加える機能を実装しました。

---

Big Wave prototype/Assets/Main Camera Blends.asset
Big Wave prototype/Assets/Main Camera Blends.asset.meta
Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/CinemachineScripts/CinemachineExtend_Look.cs
Big Wave prototype/Assets/Script/CinemachineScripts/CinemachineTest.cs
Big Wave prototype/Assets/Script/CinemachineScripts/CinemachineTest.cs.meta

まだ試作段階ですがカメラの動きを少し変えてみました

---

Big Wave prototype/Assets/Scenes/MenuScene.unity

menuSceneを更新できていなかったので、プッシュしました。

メニューシーンの更新

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/AnimationScript/Player/PlayerDeadMotion.cs
Big Wave prototype/Assets/Script/AnimationScript/Player/PlayerDeadMotion.cs.meta
Big Wave prototype/Assets/Script/EtcScript/GameSet/DeadEffect.cs
Big Wave prototype/Assets/Script/EtcScript/GameSet/DefeatEnemyEffect.cs
Big Wave prototype/Assets/Script/EtcScript/GameSet/TimeUpEffect.cs
Big Wave prototype/Assets/Script/PlayerEnemyCommonScript/HP.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTirck-related/ChargeTrickEffect.cs
Big Wave prototype/Assets/Script/PlayerScript/ChargeTirck-related/ChargeTrickEffect.cs.meta
Big Wave prototype/Assets/Script/PlayerScript/ChargeTirck-related/ChargeTrickPoint.cs
Big Wave prototype/Assets/Script/PlayerScript/JudgeChargeTrickPointNow.cs
Big Wave prototype/Assets/Script/ScoreScript/TimeLimit.cs

追記:プレイヤーの方にまだ死亡モーションがないため代わりにデバッグログでサーフ君に断末魔をあげさせてます(モーション入り次第入れておきます)

ゲームオーバーの演出を作りました

---

Big Wave prototype/Assets/Scenes/SampleScene.unity
Big Wave prototype/Assets/Script/EtcScript/GameStart/MovieCameraEvent.cs

AudioManager>StartMovieBGMからムービー中のBGMを変えられます(現在仮でゲーム中のBGMをいれてあります)

スタート時の効果音の調整、ムービー中のBGMを設定可能なようにスクリプトの修正

---

Big Wave prototype/Assets/Animation/UI/Button/StageSelectButton.controller
Big Wave prototype/Assets/Animation/UI/Button/StageSelectButton.controller.meta
Big Wave prototype/Assets/Prefab/UI/Button/StageSelectButton.prefab
Big Wave prototype/Assets/Prefab/UI/Button/StageSelectButton.prefab.meta
Big Wave prototype/Assets/Scenes/ClearScene.unity
Big Wave prototype/Assets/Scenes/GameoverScene.unity
Big Wave prototype/Assets/Scenes/MenuScene.unity
Big Wave prototype/Assets/Scenes/StageSelectScene.unity
Big Wave prototype/Assets/Scenes/StageSelectScene.unity.meta
Big Wave prototype/Assets/Script/SceneScript/SceneController.cs
Big Wave prototype/Assets/Script/UIScript/ButtonAction/CustomButtonEvent.cs
Big Wave prototype/ProjectSettings/EditorBuildSettings.asset

追記:ステージ選択画面にアニメーターコントローラのみを使い動きをつけて作ったボタンを置いてみました(Time.deltaTimeに影響されないよう設定してあるのでポーズ中でも問題なく動きます)

ステージ選択画面の骨組みを作りました(今週の土日に色々演出とか付け足す作業をします)

---

Big Wave prototype/Assets/Model/kuromakuro_model05/kuromakuro_model_05.unitypackage.meta
Big Wave prototype/Assets/Scenes/GameSceneStage1.unity
Big Wave prototype/Assets/Scenes/GameSceneStage2.unity
Big Wave prototype/Assets/Script/CommonObjectScript/Follow.meta
Big Wave prototype/Assets/Script/CommonObjectScript/Follow/FollowPassOfObject.cs
Big Wave prototype/Assets/Script/CommonObjectScript/Follow/FollowPassOfObject.cs.meta
Big Wave prototype/Assets/Script/CommonObjectScript/Follow/SwitchFollowMode_GamePos.cs
Big Wave prototype/Assets/Script/CommonObjectScript/Follow/SwitchFollowMode_GamePos.cs.meta
Big Wave prototype/Assets/Script/EnemyBulletScript/Common/AttackOfBullet.cs
Big Wave prototype/ProjectSettings/TimeManager.asset

fpsの状況によって追従速度が遅くなったりするバグが発生していたので、fpsに左右されないように追跡するようにしました。

GamePosがSpawnPointを追跡するスクリプトの修正
